spring:
  application:
    name: Scrum Board

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driverClassName: org.postgresql.Driver
    platform: postgresql

    max-idle: 50
    suspect-timeout: 60
    time-between-eviction-runs-millis: 30000

    test-on-borrow: true
    test-while-idle: true
    validation-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
